spring:
  application:
    name: zirliock-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          search-paths: /zirliockcoffe-back/configuraciones
          uri: https://github.com/DavidPerezAntonio51/Cafeteria
server:
  port: 8081