server:
  port: 8085
spring:
  mvc:
    converters:
      preferred-json-mapper: gson
  data:
    mongodb:
      uri: mongodb+srv://Dezkser:Jeff1234@cafeteriapersonal.e5clx.mongodb.net/Empleados?retryWrites=true&w=majority